services:
  - type: web
    name: smartstock-backend
    runtime: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/enterprise-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: PORT
        value: 8080
